stages:
  - build
  - deploy
build:css:
  image: node:latest
  stage: build
  script:
    - echo "Building..."
    - npm install
    - npm install node-sass
    - npm run build:sass
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    name: cssToDeploy
    when: on_success
    paths:
      - dist
deploy:
  stage: deploy
  dependencies:
    - build:css
  script:
#    - ls ./dist/
#    - ls /
#    - ls /home/
#    - mkdir /home/web/
#    - mkdir /home/web/cdn/
#    - mkdir /home/web/cdn/$CI_BUILD_REF/
#    - mkdir -p /home/web/cdn/latest/
#    - rm /home/web/cdn/latest/ -R
#    - mkdir /home/web/cdn/latest/
    - cp -r ./dist/ ./$CI_BUILD_REF/
    - cp -r ./dist/ ./latest/
    - rm -R ./dist/
