stages:
  - build
  - deploy
build:css:
  image: node:latest
  stage: build
  script:
    - echo "Building..."
    - npm install
    - npm install node-sass
    - npm run build:sass
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    name: cssToDeploy
    when: on_success
    paths:
      - dist
deploy:
  stage: deploy
  image: node:latest
  before_script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

  dependencies:
    - build:css
  script:
    - mkdir -p /builds/deployer/
    - rm -Rf /builds/deployer/*
    - mkdir -p /builds/deployer/$CI_BUILD_REF/
    - mkdir -p /builds/deployer/latest/
    - cp -r ./dist/* /builds/deployer/$CI_BUILD_REF/
    - cp -r ./dist/* /builds/deployer/latest/
    - ssh -o StrictHostKeyChecking=no deployer@164.132.103.245 "rm -Rf /home/deployer/uxui/www/latest/"
    - scp -r /builds/deployer/$CI_BUILD_REF deployer@164.132.103.245:/home/deployer/uxui/www
    - scp -r /builds/deployer/latest deployer@164.132.103.245:/home/deployer/uxui/www
