stages:
  - build
  - deploy
build:css:
  image: node:latest
  stage: build
  script:
    - echo "Building..."
    - npm install
    - npm install node-sass
    - npm run build:sass
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    name: cssToDeploy
    when: on_success
    paths:
      - css
deploy:
  stage: deploy
  dependencies:
    - build:css
  script:
    - ls ./css/
    - cp ./css/ /home/web/cdn/$CI_BUILD_REF/
