stages:
  - build
  - deploy
build:css:
  image: node:latest
  stage: build
  script:
    - echo "Building..."
    - npm install
    - npm install node-sass
    - npm run build:sass
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    name: cssToDeploy
    when: on_success
    paths:
      - dist
deploy:
  stage: deploy
  volumes_from
  dependencies:
    - build:css
  volumes:
    - builds/:builds/ ro|rw persist
  script:
    - echo "the project directory is - $CI_PROJECT_DIR"
    - echo "Where am I? - $PWD"
    - ls ./dist/
    - ls /builds/
    - mkdir -p /builds/$CI_BUILD_REF/
    - mkdir -p /builds/latest/
    - cp -r ./dist/ /builds/$CI_BUILD_REF/
    - cp -r ./dist/ /builds/latest/
