stages:
  - build
  - deploy
build:css:
  image: node:latest
  stage: build
  script:
    - echo "Building..."
    - npm install
    - npm install node-sass
    - npm run build:sass
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    name: cssToDeploy
    when: on_success
    paths:
      - css
deploy:
  stage: deploy
  dependencies:
    - build:css
  script:
    - ls ./css/
    - mkdir /home/web/
    - mkdir /home/web/cdn/
    - mkdir /home/web/cdn/$CI_BUILD_REF/
    - rm /home/web/cdn/latest/
    - mkdir /home/web/cdn/latest/
    - cp -r ./css/ /home/web/cdn/$CI_BUILD_REF/
    - cp -r ./css/ /home/web/cdn/latest/
