# This is a basic workflow to help you get started with Actions
name: CI_Manual

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo echo "Building..."
          npm install
          npm install node-sass
          npm run build:sass
          echo "Build successful"

      - name: Copy prod to dist artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/


      - name: Add and Commit changes to master
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git pull
          git rm dist/* -rf
          git add dist/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.0.4
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
#          head: pr-pages
#          base: gh-pages
          title: 'Updates site files from latest Actions build'
          body: >
            Build CSS

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: test
          SLACK_COLOR: '#3278BD'
          SLACK_USERNAME: Github bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}